cors:
  originPatterns: http://localhost:8080,https://erudio.com.br,https://localhost:3000
file:
  upload-dir: D:/UploadDir
security:
  jwt:
    token:
      secret-key: 53cr37
      expired-length: 3600000
spring:
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/rest_with_spring_boot_udemy?useTimezone=true&serverTimezone=UTC
      username: root
      password: root123
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
      show-sql: false
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200KB
      max-request-size: 215MB
springdoc:
  paths-to-match:
    - /auth/**
    - /api/**/v1/**
  swagger-ui:
    use-root-path: true